server:
  port: 8080
  servlet:
    context-path: /backend-service

spring:
  application:
    name: backend-service
  datasource:
    #    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/backend_service}
    url: ${DATASOURCE_URL:jdbc:mysql://root:baecNhfJwgDwYfdapcMYQYjKxCuIecdZ@roundhouse.proxy.rlwy.net:35733/railway}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:baecNhfJwgDwYfdapcMYQYjKxCuIecdZ}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        boot:
          allow_jdbc_metadata_access: false
    show-sql: false
    hibernate:
      ddl-auto: update
  messages:
    basename: i18n/messages
    encoding: UTF-8
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
  refresh-token:
    expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: '*'

